ROOT_WIDTH=700
ROOT_HEIGHT=600

TOP_WIDTH=700
TOP_HEIGHT=100

BUTTON_FRAME_WIDTH=460
BUTTON_FRAME_HEIGHT  = ROOT_HEIGHT - TOP_HEIGHT

HISTORY_FRAME_WIDTH  = ROOT_WIDTH - BUTTON_FRAME_WIDTH
HISTORY_FRAME_HEIGHT = BUTTON_FRAME_HEIGHT

BUTTON_WIDTH  = 6
BUTTON_HEIGHT = 6

SIMPLE_BUTTONS = [
        'C', '/', 'X',   '<-',
        '7', '8', '9',   '*',
        '4', '5', '6',   '-',
        '1', '2', '3',   '+',
        '0', '.', '+/-', '='
        ]
